# Use postgres/example user/password credentials
version: "3.1"

services:
  backend:
    image: eriizu/pwa-course-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pwa.rule=Host(`pwa-back.eriizu.fr`)"
      - "traefik.http.routers.pwa.entrypoints=websecure"
      - "traefik.http.routers.pwa.tls.certresolver=le"
    environment:
      PORT: 80
    links:
      - "db"
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file: conf.env
    # environment:
    #   POSTGRES_PASSWORD: pwa
    #   POSTGRES_USER: pwa
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
